### ISSUE TITLE
Server Request Manager

### ISSUE THREAD

**Issue by emilyabest** [quirky-quokkas/snapcycle#10]
ServerRequestManager will handle all interactions with the server. Needed methods include:
- shared
- registerUser:(SnapUser *) user
- loginUser: username, password
- (array of category objects *) getAllCategories
- logTrash:(Trash *)t -> for current user

**Comment by taylor-ka** [comment]
Ended up not being a good design decision, so aborting
Many methods were one liners
Easier to deal with errors in the class that we need the Parse request in
